### PR TITLE
Format codebase, fix lint errors, add GitHub actions to check pull re…

### LINKED ISSUE #26: Format codebase follow-up: Fix TypeErrors
> could u give an example of the type errors? will probably open new PR for type error checks

Just got back to my laptop, here's the full breakdown:

```
src/api/commander.ts(29,10): error TS2454: Variable 'res' is used before being assigned.
src/app/commanders/page.tsx(56,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/app/commanders/page.tsx(57,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/app/commanders/page.tsx(58,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/app/commanders/page.tsx(59,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/constants/filters.ts(3,29): error TS2307: Cannot find module './allFilters' or its corresponding type declarations.
src/context/filter.tsx(2,29): error TS2307: Cannot find module '@/constants/allFilters' or its corresponding type declarations.
```

_Originally posted by @rrdelaney in https://github.com/EDH-Top-16/edhtop16-v2/issues/24#issuecomment-1805049339_

### PR DESCRIPTION
**Pull request by rrdelaney**
Fixes #26 

[Recommend reviewing with whitespace hidden.](https://github.com/EDH-Top-16/edhtop16-v2/pull/24/files?diff=split&w=1)

Yea this is quite the PR, but basically what I did was:

```sh
$ black server
$ cd client && npx prettier --write .
```

And then fix a few lint errors that were coming up from `npx next lint`. I wasn't able to enable a check for type-checking the client codebase as there were already a few type errors that seemed out of scope for this PR.

### CODE REVIEW

**Comment by g00gol** [comment]
could u give an example of the type errors? will probably open new PR for type error checks

**Comment by rrdelaney** [comment]
> could u give an example of the type errors? will probably open new PR for type error checks

Just got back to my laptop, here's the full breakdown:

```
src/api/commander.ts(29,10): error TS2454: Variable 'res' is used before being assigned.
src/app/commanders/page.tsx(56,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/app/commanders/page.tsx(57,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/app/commanders/page.tsx(58,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/app/commanders/page.tsx(59,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
  No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
src/constants/filters.ts(3,29): error TS2307: Cannot find module './allFilters' or its corresponding type declarations.
src/context/filter.tsx(2,29): error TS2307: Cannot find module '@/constants/allFilters' or its corresponding type declarations.
```

**Comment by g00gol** [comment]
> > could u give an example of the type errors? will probably open new PR for type error checks
> 
> Just got back to my laptop, here's the full breakdown:
> 
> ```
> src/api/commander.ts(29,10): error TS2454: Variable 'res' is used before being assigned.
> src/app/commanders/page.tsx(56,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
>   No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
> src/app/commanders/page.tsx(57,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
>   No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
> src/app/commanders/page.tsx(58,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
>   No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
> src/app/commanders/page.tsx(59,20): error TS7053: Element implicitly has an 'any' type because expression of type 'string' can't be used to index type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
>   No index signature with a parameter of type 'string' was found on type '{ commanders: Record<string, { colorID?: string | undefined; wins?: number | undefined; winsSwiss?: number | undefined; winsBracket?: number | undefined; draws?: number | undefined; losses?: number | undefined; ... 5 more ...; winRateBracket?: number | undefined; }>; }'.
> src/constants/filters.ts(3,29): error TS2307: Cannot find module './allFilters' or its corresponding type declarations.
> src/context/filter.tsx(2,29): error TS2307: Cannot find module '@/constants/allFilters' or its corresponding type declarations.
> ```

thanks! ill open another issue for these bugs

**Comment by rrdelaney** [comment]
@g00gol I fixed those type errors in the second commit in this PR, for review here: https://github.com/EDH-Top-16/edhtop16-v2/pull/24/commits/2f7bdaad309199e1c5d737c7c92b7795bc35a58a

**Comment by g00gol** [comment]
@rrdelaney looks great! sorry for not seeing this sooner. im approving it now

**Review by g00gol — APPROVED** [review]
lgtm

**Pull request merged**
