### PR TITLE
Add basic docker-compose and Dockerfile

### PR DESCRIPTION
**Pull request by danmudd**
## Context
This PR adds a basic Dockerfile and docker-compose setup - `mongodb` doesn't always play nicely on everyone's system and this makes it a little nicer to work in.

### CODE REVIEW

**Comment by g00gol** [comment]
basic dockerfile lgtm. awaiting review from @JasonQiu21

**Review by g00gol — APPROVED** [review]
lgtm

**Comment by JasonQiu21** [comment]
@danmudd can you add a bit to the readme on how to use? I've had people approach me with a little less experience in deploying projects

**Review by JasonQiu21 — CHANGES_REQUESTED** [review]
@danmudd can you add a bit to the readme on how to use? I've had people approach me with a little less experience in deploying projects

**Review by JasonQiu21 — APPROVED** [review]
Looks good, thanks a lot for this!

**Pull request merged**
