### PR TITLE
Add routing to get unaggregated entries

### PR DESCRIPTION
**Pull request by JasonQiu21**

### CODE REVIEW

**Comment by g00gol** [comment]
@JasonQiu21 `/commanders` works with minimal inputs on client. I'll test thoroughly later on. Please help with that

**Comment by JasonQiu21** [comment]
@g00gol Added a new route and server-side CR calculation

**Comment by g00gol** [comment]
@JasonQiu21 Go through Postman requests to make sure returned data is valid. Attach a screenshot

**Comment by JasonQiu21** [comment]
image
image
image

**Comment by JasonQiu21** [comment]
Route `get_commanders` still works as usual, commanders just have `topCuts` and `conversionRate` attached to them now

**Review by g00gol — APPROVED** [review]

**Pull request merged**
